plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaExec) {
    systemProperty "file.encoding", "UTF-8"
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation project(':Common')
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.register('copyTestScripts', Copy) {
    from 'src/test/resources/scripts'
    into 'build/libs/scripts'
    // Если тесты запускаются внутри build/classes/java/test или build/resources/test,
    // можно продублировать копирование туда, но обычно для запуска из под джарника
    // файлы должны лежать рядом с ним:
    into 'build/resources/test/scripts'
}

// Указываем, что перед тестированием нужно обязательно скопировать скрипты
processTestResources.dependsOn copyTestScripts

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-Class': 'Client'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from configurations.runtimeClasspath.collect {
        it.isDirectory() ? it : zipTree(it)
    }
}